#!/usr/bin/env bash

cat /dev/null > /tmp/docker-machine.json
args=$(printf "%q\t" "$@")
ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -t docker-machine \
    "$args" >> /tmp/docker-machine.json
cat /tmp/docker-machine.json
